### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by mediumhust** [Q42/fabricjs-opentypejs-demo#2]
Hi, this is a awesome plugin.
Please check your demo again.
Could you show result of canvas.toSVG()

**Comment by lukasvan3l** [comment]
The code is two years old and it worked at the time in all major browsers.
It could very well be that it doesn't work in specific browsers or versions. If you provide me a bit more details (what OS & browser are you running, error messages, screenshots, etc) then I might find some time to dive further into it.

**Comment by mediumhust** [comment]
I tested in: https://q42.github.io/fabricjs-opentypejs-demo/
It doesn't work in all OSs and browsers: http://prntscr.com/oul7on

Could you show a result of svg with outline of text?

**Comment by mediumhust** [comment]
I can fix that error but I want to know the way opentypejs resolve the problem with outline text in exported SVG. Some of our  printing system doesn't accept PDF with embed font, we need to convert text in svg to outline. Do you have any idea? Thank you very much for your response.

**Comment by lukasvan3l** [comment]
I fixed a bug in the demo, now it "works on my machine".
You can type `canvas.toSVG()` in the console if you need, the `canvas` element is set on `window.canvas`.
I don't know if this will help you converting text to outline, I'm not outputting the outlines, but using them during the rendering in FabricJS.

Closing because it's probably outdated ;)
